version: '3'

services:
  proxy:
    build:
      context: ./proxy
    container_name: cs_prod_proxy
    restart: always
    ports:
      - 80:80
    networks:
      - app
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: ./backend
      target: production
    container_name: cs_prod_backend
    restart: always
    ports:
      - 3000:80
    env_file:
      - ./backend/.env
    networks:
      - app
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
      target: production
    container_name: cs_prod_frontend
    restart: always
    ports:
      - 3001:80
    env_file:
      - ./backend/.env
    networks:
      - app
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    container_name: cs_prod_mysql
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: '12345'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: 'collab_space'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: '12345'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - app

networks:
  app:
volumes:
  mysql:
